export enum TestID {
  // Components
  TIME_SERIES_CHART = 'TIME_SERIES_CHART',
  DATE_PICKER_PAIR = 'DATE_PICKER_PAIR',
  DROPDOWN_SELECTOR = 'DROPDOWN_SELECTOR',

  // Page
  ERROR_BOUNDARY_PAGE = 'ERROR_BOUNDARY_PAGE',
}
